---
metadata:
    title: REAPER Made Easy
    description: |
        REAPER Made Easy: Free Training from TGV Productions

        REAPER is an accessible and affordable digital audio workstation (DAW). It can be used to compose, record, edit, mix and master pretty much any musical or audio-based thing you could name.
        In  this feed, you’ll find an expanding collection of free training content, all tailored toward using REAPER with screen reader software. We’re calling it the REAPER Made Easy project.

          Scott Chesworth
          Jenny K. Brennan
    language: en-us
    link: https://www.theglobalvoice.info/reaper/
    itunes_image: https://theglobalvoice.info/reaper_files/podcast/Artwork/Show%20Cover.png
    itunes_category: Education
    itunes_explicit: false
    itunes_author: Reaper made Easy
    itunes_email: reapermadeeasy@gmail.com
    rss_feed_url: https://reaperteacher.com/rss.xml

episodes:
    - title: "01 - Reaper made Easy - What's this then? With Scott and JennyK "
      description:
          "Welcome to the Reaper Made Easy Podcast where hosts Scott and JennyK attempt to describe what this podcast is, isn't, and might become.
          [Visit ReaperTeacher for more about our monthly Q&A and more](https://reaperteacher.com)."
      publication_date: "2025-05-22T10:00:00"
      asset_url: "https://theglobalvoice.info/reaper_files/podcast/01-ReaperMadeEasy.mp3"
      episode: 0
      season: 1
      episode_type: "full"
      itunes_image: https://theglobalvoice.info/reaper_files/podcast/Artwork/Episode%20Artwork.png
      link: https://www.theglobalvoice.info/reaper/

