---
metadata:
    title: REAPER Made Easy
    description: |
        REAPER Made Easy: Free Training from TGV Productions

        REAPER is an accessible and affordable digital audio workstation (DAW). It can be used to compose, record, edit, mix and master pretty much any musical or audio-based thing you could name.
        In  this feed, you’ll find an expanding collection of free training content, all tailored toward using REAPER with screen reader software. We’re calling it the REAPER Made Easy project.

          Scott Chesworth
          Jenny K. Brennan
    language: en-us
    link: https://www.theglobalvoice.info/reaper/
    itunes_image: https://theglobalvoice.info/reaper_files/podcast/Artwork/Show%20Cover.png
    itunes_category: Education
    itunes_explicit: false
    itunes_author: Reaper made Easy
    itunes_email: reapermadeeasy@gmail.com
    rss_feed_url: https://reaperteacher.com/rss.xml

episodes:
    - title: "Reaper made Easy - What's this then? With Scott and JennyK "
      description:
          "Welcome to the Reaper Made Easy Podcast. This is where hosts Scott and JennyK attempt to describe what this podcast is, isn't, and might become.
          [Visit ReaperTeacher for more about our monthly Q&A and more](https://reaperteacher.com)."
      publication_date: "2025-05-22T10:00:00"
      asset_url: "https://theglobalvoice.info/reaper_files/podcast/00-ReaperMadeEasy.mp3"
      episode: 0
      season: 1
      episode_type: "full"
      itunes_image: https://theglobalvoice.info/reaper_files/podcast/Artwork/Episode%20Artwork.png
      link: https://www.theglobalvoice.info/reaper/
    - title: "REAPER made Easy - As You Start"
      description:
          "as you start digging into REAPER, there are some resources you'll want to know about. They'll make it easier to learn the ropes. 
          In this episode, JennyK and Scott give you a rundown of where to find guides that'll help you get everything installed and configured for accessibility, where to find free training, and groups you can join with other REAPER/OSARA users who'll be happy to share their knowledge.
          After listening to this you will know where to turn when questions start cropping up. All links mentioned throughout this episode are listed here.

          Getting the software:
          [REAPER](https://www.reaper.fm/)
          [OSARA](https://osara.reaperaccessibility.com/)
          [SWS](https://sws-extension.org/)

          Training Resources:
          [REAPER Made Easy, free training sponsored by TGV Productions](https://www.theglobalvoice.info/reaper/)
          [The REAPER Accessibility Wiki](https://www.reaperaccessibility.com/wiki/Main_Page)
          [The Hoard](https://hoard.reaperaccessibility.com/)

          Groups to Discuss REAPER Accessibility:
                    [RWP email list on the web (Reapers Without Peepers](https://groups.io/g/rwp)
          Or you can join by sending a blank email to rwp+subscribe@groups.io  
          [Join the REAPER Access group on Whatsapp](www.tiny.cc/ReaperAccess)
          
          Join us for live Q&A on the last Saturday of each month. Find all the details here:
          [I'm Perplexed, What's Next? The monthly live Q&A with Scott and JennyK](https://reaperteacher.com/)

          Produced by JennyK and Scott Chesworth for REAPER Made Easy. "
      publication_date: "2025-06-14T10:00:00"
      asset_url: "https://theglobalvoice.info/reaper_files/podcast/01-ReaperMadeEasy-AsYouStart.mp3"
      episode: 1
      season: 1
      episode_type: "full"
      itunes_image: https://theglobalvoice.info/reaper_files/podcast/Artwork/Episode%20Artwork.png
      link: https://www.theglobalvoice.info/reaper/
