---
metadata:
  title: REAPER Made Easy1
  description: |
    A podcast about various topics. This block can be formatted using Markdown, with things like lists:

      * List item 1
      * List item 2
  language: en-us

  link: https://www.theglobalvoice.info/reaper/
  itunes_image: http://example.com/images/podcast-cover.jpg
  itunes_category: Education
  itunes_explicit: false
  itunes_author: Reaper made Easy
  itunes_email: training@theglobalvoice.info
  rss_feed_url: https://reaperteacher.com/rss.xml
episodes:
  - title: Core Concepts with Justin and Scott
    description: >-
      Join Scott Chesworth and Justin Macleod as they explain and
      illustrate the core concepts of a REAPER project. Whether this is your
      first foray into audio production or you’re considering switching over
      from some other recording software, this is where to start. There’s
      informative talk, there are working examples, it’s 18 minutes well spent.

      [Visit ReaperTeacher for more about our monthly Q&A and more](https://reaperteacher.com).
    publication_date: "2023-02-01T10:00:00"
    asset_url: https://theglobalvoice.info/reaper_files/Core%20Concepts%20with%20Justin%20and%20Scott.mp3
    episode: 1
    season: 1
    episode_type: full
    itunes_image: http://example.com/images/episode1.jpg
    link: https://www.theglobalvoice.info/reaper/
